### ISSUE TITLE
correction fichier stoa0043.stoa001.digilibLT-lat1.xml

### ISSUE THREAD

**Issue by saintakim** [Chartes-TNAH/digiliblt#12]

**Comment by saintakim** [comment]
Correction de mon premier fichier xml
Chemin : "digiliblt/data/stoa0043/stoa001/toa0043.stoa001.digilibLT-lat1.xml

- [ ] Passage level parsing   

- [ ] Unique nodes found by XPath

- [ ] Empty References 

- [ ] Word Counting

**Comment by PonteIneptique** [comment]
Closed by #87
