### ISSUE TITLE
correction fichier stoa0293b.stoa003.digilibLT-lat1.xml

### ISSUE THREAD

**Issue by LilyG98** [Chartes-TNAH/digiliblt#14]
Validation du cours Git du M1 HN 1/5 :  correction du fichier stoa0293b.stoa003.digilibLT-lat1.xml

**Comment by LilyG98** [comment]
Bonjour Monsieur, 
Le fichier que j'ai choisi ne comporte que des balises `<p>` (12 au total) et ne fait pas référence à des chapitres ou livres. 

Je suis allée lire la documentation digitlib de l'extrait de que j'ai choisi de "Epitome anonyma (quae gynaecia uocatur)" (https://digiliblt.uniupo.it/opera.php?gruppo=opere&iniziale=all&id=dlt000513) et celle-ci mentionne bien des chapitres différents, que l'on retrouve d'ailleurs dans certains autres XML du même ouvrage. Faut-il numéroter les paragraphes? 

Sinon, j'ai identifié une différence de référence de langue. ligne 79 il y a écrit "la" au lieu de "lat", que l'on retrouve bien dans l'élément <body> ligne 90 mais Oxygen ne me met aucune erreur.

**Comment by PonteIneptique** [comment]
Rien de grave, mais attention à utiliser les \` quand vous citez des balises (j'ai corrigé votre commentaire si vous voulez voir ce que je veux dire). Dans ce contexte, il y a deux stratégies: créer une balise <div> englobante avec un numéro inintéressant, ou numéroter les paragraphes. J'aurais tendance à numéroter les paragraphes.

**Comment by LilyG98** [comment]
D'accord ! 
Merci

**Comment by LilyG98** [comment]
Je n'ai pas accès au Hooktest depuis mon fork et ma branche tandis que j'ai fait déjà fait 2 push. Il est écrit qu'il n'y a aucun workflow. Comment puis-je y remédier?

**Comment by PonteIneptique** [comment]
J'aurais tendance à pencher pour github actions non activé, vu que les actions sont bien listées. ( https://github.com/LilyG98/digiliblt/actions/workflows/hooktest.yml )

**Comment by LilyG98** [comment]
J'ai revérifié,le github actions est bien activé :'(

**Comment by PonteIneptique** [comment]
Il est possible de faire tourner hooktest localement au pire, c'est assez facile après quelques mois de python et autre joyeuseté.

**Comment by LilyG98** [comment]
Le hooktest fonctionne désormais dans "Actions" !

**Comment by PonteIneptique** [comment]
Fixes #30
