### ISSUE TITLE
Correction du document 'phi1363.phi002.digilibLT-lat1.xml'

### ISSUE THREAD

**Issue by Ammeister** [Chartes-TNAH/digiliblt#2]
Dans le cadre de l'évalutation du cours de GIT du master HN, nous devons corriger 5 document xml CapiTainS issus du projet DigilibLT. Celui-ci est mon premier.
Le chemin jusqu'au document concerné est le suivant : 'digiliblt/data/phi1363/phi002/phi1363.phi002.digilibLT-lat1.xml'.
Erreurs à corriger :
- [x] Passage level parsing.
- [x] Unique nodes found by XPath.
- [x] Empty References.
- [x] Word Counting.

**Comment by Ammeister** [comment]
@PonteIneptique
Est-ce que c'est possible de nous nous expliquer à quoi correspondent les erreurs suivantes ? Ce sont celles qui concernent l'écrasante majorité des documents présentant des erreurs selon le Hooktest :

    Passage level parsing.
    Unique nodes found by XPath.
    Empty References.
    Word Counting.

De plus, j'ai modifié le document sur lequel j'ai ouvert une issue et il n'apparaît plus dans les documents traités par le Hooktest après que celui-i secisoit exécuté à la suite d'un push sur ma branche. Est-ce normal ?
Si non, que puis-je faire pour remédier à cela ?

**Comment by PonteIneptique** [comment]
1. <kbd>Passage level parsing</kbd> indique qu'il n'a pas été possible pour HookTest de trouver des passages avec le modèle de citation donné.
2. <kbd>Unique nodes found by XPath</kbd> indique que le même xPath a convenu à "plusieurs noeuds" de citation. Cependant, dans le cas où <kbd>Passage..</kbd> a fait défaut, je n'y ferai pas attention.
3. <kbd>Empty References</kbd> indique que des noeuds de citations n'ont pas de valeur de citation. En gros, `/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']` trouve des identifiants de passages vides. Encore une fois, c'est pour moi une conséquence de (1)
4. Le système n'a pas réussi à compter les mots

Il me faudrait un lien pour un avis sur votre problème de branche ;)

**Comment by PonteIneptique** [comment]
Après une courte investigation, voici la solution pour votre problème hooktest: le fichier fonctionne, mais hooktest n'affiche pas les textes avec `--verbose 5`: https://github.com/Chartes-TNAH/digiliblt/commit/368fcafc52e227389a3e07b17d301344d97877d5

**Comment by Ammeister** [comment]
> Après une courte investigation, voici la solution pour votre problème hooktest: le fichier fonctionne, mais hooktest n'affiche pas les textes avec `--verbose 5`: [368fcaf](https://github.com/Chartes-TNAH/digiliblt/commit/368fcafc52e227389a3e07b17d301344d97877d5)

Bonjour,
Merci beaucoup j'ai procédé à la modification et ça a fonctionné.
![Capture d’écran du 2021-04-01 14-37-27](https://user-images.githubusercontent.com/72987654/113295017-ee72a400-92f7-11eb-85fd-5c1672aaa763.png)

**Comment by PonteIneptique** [comment]
J'attends donc votre pull request ;)

**Comment by PonteIneptique** [comment]
Closed by #4
