### ISSUE TITLE
Correction fichier "phi963.phi002.digilibLT-lat1.xml"

### ISSUE THREAD

**Issue by Ammeister** [Chartes-TNAH/digiliblt#22]
Dans le cadre de l'évalutation du cours de GIT du master HN, nous devons corriger 5 document xml CapiTainS issus du projet DigilibLT. Celui-ci est mon dernier.
Le chemin jusqu'au document concerné est le suivant : 'digiliblt/data/phi963/phi002/phi963.phi002.digilibLT-lat1.xml'.
Erreurs à corriger :

- [x] Passage level parsing.
- [x] Unique nodes found by XPath.
- [x] Empty References.
- [x] Word Counting.

**Comment by Ammeister** [comment]
@PonteIneptique , Le fichier a été corrigé, mais je me pose une question et vous pourrez sans doute éclairer ma chandelle.
après la première balise div, une balise p contient tout le texte de la section. dans cette balise p on retrouve des balises milestone typées "par" donc ce sont les paragraphes. Souhaitez-vous que j'opère la transformation des balises milestones "par" en balises div "par" ? Exemple :

```xml
<div type="section" n="1">
            <head>I. De nomine</head>
            <p>
               <milestone unit="row" n="riga 2 vol. V Keil"/>
               <milestone unit="par" n="1"/> Omnia nomina quinque vocalibus ablativo casu terminantur, ‛a’ ‛e’
     ‛i’ ‛o’ ‛u’, id est quicquid declinaveris de nomine ablativum casum in has litteras ducit, ut
     puta ‛haec Iulia ab hac Iulia’, ‛hic paries ab hoc pariete’, ‛agilis ab agili’, ‛doctus a
     docto’, ‛hic versus ab hoc versu’; <milestone unit="par" n="2"/>praeter pauca aptota, quae nos
     turbare non debent quia pauca sunt, ut puta ‛nequam homo’ ‛a nequam’ dicimus, ‛nugas homo’ ‛a
     nugas’ dicimus: hic videtur ablativus suscepisse ‛m’ et ‛s’, sed in aptotis, non in legitimis
     et regularibus nominibus quae certo ordine declinantur.<lb/>
```

**Comment by PonteIneptique** [comment]
En effet, soit en seg, soit en p numérotés, si vous avez le temps et l'envie ;)
Pour aller plus loin, je suis ouvert à des sujestions de tag pour les ```‛agilis ab agili’```. Il semble que ce soit des exemples mis en exergue mais...
