### ISSUE TITLE
Correction du fichier "stoa0058.stoa021.digilibLT-lat1.xml"

### ISSUE THREAD

**Issue by FraDarklands** [Chartes-TNAH/digiliblt#3]
Bonjour,
Je me charge de la correction du fichier "stoa0058.stoa021.digilibLT-lat1.xml" pour l'évaluation du cours de GIT des M1 Humanités numériques.
Le chemin pour parvenir au fichier: "digiliblt/data/stoa0058/stoa021/stoa0058.stoa021.digilibLT-lat1.xml"
Celui-ci est mon premier fichier sur les 5 à rendre. Les erreurs présentes dans le fichier que je me propose de corriger sont les suivantes:

- [x] Passage level parsing

- [x] Unique nodes found by XPath

- [x] Empty References

- [x] Word Counting

**Comment by PonteIneptique** [comment]
Fixed by #72
