### ISSUE TITLE
"Correction du fichier "stoa0357c.stoa001.digilibLT-lat1.xml"

### ISSUE THREAD

**Issue by EtienneFerrandi** [Chartes-TNAH/digiliblt#49]
Fichier XML CapiTains  3/5 à corriger pour la validation du cours Git du master HN.
Le chemin vers le fichier est le suivant : data/stoa0357c/stoa001/stoa0357c.stoa001.digilibLT-lat1.xml.
Erreurs relevées par le Hooktest à corriger :
"Duplicate nodes found : [...]
stoa0357c.stoa001.digilibLT-lat1.xml	1, 10, 100, 101, 102, 103, 1036, 104, 105, 106, 107, 108, 109, 1096, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 12, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 13, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 14, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 15, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 16, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 17, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 19, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 2, 20, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 21, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 22, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 23, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 24, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 25, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 26, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 27, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 28, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 29, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 3, 30, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 31, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 32, 321, 322, 323, 324, 325, 326, 327, 328, 329, 33, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 34, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 35, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 36, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 37, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 38, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 39, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 4, 40, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 41, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 42, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 43, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 44, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 45, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 46, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 47, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 48, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 49, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 5, 50, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 51, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 52, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 53, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 54, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 55, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 56, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 57, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 58, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 59, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 6, 60, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 61, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 62, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 63, 630, 631, 632, 633, 635, 636, 637, 638, 639, 64, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 65, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 66, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 67, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 68, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 69, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 7, 70, 700, 701, 702, 703, 704, 705, 706, 707, 708, 71, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 72, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 73, 730, 731, 732, 733, 734, 737, 738, 74, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 75, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 76, 760, 761, 762, 763, 764, 765, 766, 767, 769, 77, 770, 771, 772, 773, 774, 776, 777, 778, 779, 78, 780, 781, 782, 783, 784, 785, 786, 787, 788, 79, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 8, 80, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 81, 810, 811, 812, 813, 814, 815, 817, 818, 819, 82, 820, 821, 823, 824, 825, 826, 827, 828, 83, 830, 832, 833, 834, 835, 836, 837, 84, 840, 842, 843, 845, 847, 849, 85, 851, 856, 858, 859, 86, 860, 863, 864, 865, 867, 868, 869, 87, 870, 872, 88, 887, 89, 9, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99"

**Comment by EtienneFerrandi** [comment]
Après modification, nouveau Hooktest.
Erreurs à corriger :
"Duplicates nodes found : [...]
stoa0357c.stoa001.digilibLT-lat1.xml	I.121, I.155, I.178, I.260, I.336, I.378, I.403, I.569, I.570, I.596, II.133, II.210, II.388, II.49, II.612, III.149, III.182, III.190, III.257, III.270, III.285, III.307, III.543, III.599, III.614, III.621, IV.21, IV.22, IV.257, IV.296, IV.520, IV.56, IV.639, IV.685, IV.811, IX.1036, IX.1096, IX.121, IX.178, IX.266, IX.588, IX.632, IX.646, IX.689, IX.701, IX.820, IX.887, V.133, V.138, V.225, V.392, V.585, V.629, V.701, V.713, V.737, V.778, VI.134, VI.226, VI.333, VI.334, VI.350, VI.416, VI.469, VI.479, VI.494, VI.607, VI.612, VI.683, VI.697, VI.746, VII.102, VII.131, VII.143, VII.168, VII.172, VII.197, VII.211, VII.267, VII.279, VII.334, VII.476, VII.518, VII.88, VIII.255, VIII.277, VIII.310, VIII.761, VIII.810, X.115, X.167"

**Comment by PonteIneptique** [comment]
Fixed by #67
