### ISSUE TITLE
Correction du fichier "stoa0024.stoa001.digilibLT-lat1.xml"

### ISSUE THREAD

**Issue by FraDarklands** [Chartes-TNAH/digiliblt#73]
Bonjour,
Je me charge de la correction du fichier `stoa0024.stoa001` pour l'évaluation du cours de GIT des M1 Humanités numériques.
Le chemin pour parvenir au fichier est: `digiliblt/data/stoa0024/stoa001/stoa0024.stoa001.digilibLT-lat1.xml`

Celui-ci est mon deuxième fichier sur les 5 à rendre. Les erreurs présentes dans le fichier que je me propose de corriger sont les suivantes:

- [x] Passage level parsing

- [x] Unique nodes found by XPath

- [x] Empty References

- [x] Word Counting

**Comment by PonteIneptique** [comment]
Le fichier stoa0024.stoa001 est déjà corrigé depuis deux mois:
- [Test](https://github.com/Chartes-TNAH/digiliblt/runs/2408690570#step:5:73)
- [Commit](https://github.com/Chartes-TNAH/digiliblt/commit/9b95b0faf03fa094cdb69ff895da0bde329c1963#diff-d19cddeca8b18f0dfeda510800a73ee2e6da9772cea1c777edd8a512e9d8e232)

Si vous cherchez des fichiers, certains ont été proposés ici: https://github.com/Chartes-TNAH/digiliblt/issues/8
